// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ModernBooksDEMO","status":true,"description":"Adds a new way to create and read books for your game!","parameters":{"Button Settings":"","ButtonSize":"48","ButtonPositionX":"20","ButtonPositionY":"20","ButtonColorNormal":"#000000","ButtonColorHover":"#333333","ButtonGap":"20","CloseButtonText":"auto","NextPageText":"auto","BackPageText":"auto","Sound Settings":"","ChangePageSound":"Book1","ChangePageVolume":"90","ChangePagePitch":"100"}},
{"name":"modern_book_plugin (1)","status":false,"description":"Modern-style interactive book viewer for RPG Maker MZ.","parameters":{}}
];
